# Generated by Django 4.2.5 on 2023-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_comment_created_comment_comment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
