# Generated by Django 4.2.5 on 2023-10-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_watchlist_listing_watchlist_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.listing'),
        ),
    ]
