# Generated by Django 4.2.5 on 2023-10-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comment_commenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'default_permissions': ()},
        ),
    ]
