# Generated by Django 4.2.5 on 2023-10-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
    ]
